### PR TITLE
feat(groups): Option to specify a group for a variable

### PR DESCRIPTION
**Pull request by reinzor**
The group "Default" will be set as default so no behavior will change.
However, this commit will break ABI / API compatibility.

Covers #11

### CODE REVIEW

**Comment by v-lopez** [comment]
Thanks, this looks very interesting.

Let me run it through our internal CI, and I'll get back to you next week.

**Comment by v-lopez** [comment]
I'm afraid not, but feel free to submit a PR if you manage to implement it!

**Comment by reinzor** [comment]
Sorry, I do not really follow your answer ..

**Comment by reinzor** [comment]
Oh, maybe it was an answer to https://github.com/pal-robotics/ddynamic_reconfigure/issues/11 ;)

**Comment by v-lopez** [comment]
Yeah @reinzor sorry about that, Friday morning stupidity!

**Pull request merged**
